Enhance autorevision to get the correct values on Travis-CI builds

diff --git a/build_tools/autorevision b/build_tools/autorevision
--- a/build_tools/autorevision
+++ b/build_tools/autorevision
@@ -115,6 +115,49 @@ gitRepo() {
 	VCS_EXTRA="$(git describe 2> /dev/null)"
 }
 
+# For Travis-CI builds
+travisCIBuild() {
+	# Information must be extracted from a combination of Travis-set environment
+	# variables and other sources
+
+	cd "${TRAVIS_BUILD_DIR}"
+
+	VCS_TYPE="git"
+	VCS_BASENAME="$(basename "${PWD}")"
+
+	# Check if working copy is clean, however, we will ignore any and all po files
+	# when we determine if modifications were done.
+	git update-index --assume-unchanged po/*.po
+	test -z "$(git status --untracked-files=no --porcelain)"
+	VCS_WC_MODIFIED="${?}"
+	# now, reset index back to normal
+	git update-index --no-assume-unchanged po/*.po
+
+	# The full revision hash
+	VCS_FULL_HASH="${TRAVIS_COMMIT}"
+	# The short hash
+	VCS_SHORT_HASH="$(echo "${VCS_FULL_HASH}" | cut -b 1-7)"
+
+	# Current branch
+	VCS_BRANCH="${TRAVIS_BRANCH}"
+	if [ -n "${TRAVIS_PULL_REQUEST_BRANCH}" ]; then
+		# When triggered by a pull request, TRAVIS_BRANCH is set to the *target* branch name
+		# But we want the source branch name, so use TRAVIS_PULL_REQUEST_BRANCH
+		VCS_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH}"
+	fi
+
+	# Check if we are on a tag
+	VCS_TAG=
+	if [ -n "${TRAVIS_TAG}" ]; then
+		VCS_TAG="${TRAVIS_TAG}"
+
+		# When on a tag, clear VCS_BRANCH
+		VCS_BRANCH=
+	fi
+
+	VCS_EXTRA=
+}
+
 
 # Functions to output data in different formats.
 # For header output
@@ -189,6 +232,9 @@ EOF
 if [ -f "${CACHEFILE}" ] && [ "${CACHEFORCE}" = "1" ]; then
 	# When requested only read from the cache to populate our symbols.
 	. "${CACHEFILE}"
+elif [ -n "${TRAVIS}" ] && [ "${TRAVIS}" == "true" ]; then
+	# Autorevision is being executed from a Travis-CI build
+	travisCIBuild
 elif [ ! -z "$(git rev-parse HEAD 2>/dev/null)" ]; then
 	gitRepo
 elif [ -f "${CACHEFILE}" ]; then
@@ -197,7 +243,7 @@ elif [ -f "${CACHEFILE}" ]; then
 	# Do not overwrite the cache if we know we are not going to write anything new.
 	CACHEFORCE="1"
 else
-	echo "error: No repo or cache detected." 1>&2
+	echo "error: No repo, cache, or other data source detected." 1>&2
 	exit 1
 fi
 
